version: '3.8'

services:
  backend:
    build:
      context: .
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  web:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
